sudo: required
services:
    - docker

before_install:
    - docker build -t alinro/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true alinro/react-test npm run test

after_success:
    - docker build -t alinro/docker-multi-client ./client
    - docker build -t alinro/docker-multi-nginx ./nginx
    - docker build -t alinro/docker-multi-server ./server
    - docker build -t alinro/docker-multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push alinro/docker-multi-client
    - docker push alinro/docker-multi-nginx
    - docker push alinro/docker-multi-server
    - docker push alinro/docker-multi-worker
