version: "3"
services:
  nginx:
    image: alinro/docker-multi-nginx
    hostname: nginx
    ports:
      - "80:80"
  server:
    image: alinro/docker-multi-server
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: alinro/docker-multi-client
    hostname: client
  worker:
    image: alinro/docker-multi-worker
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
