name: Publish Docker images
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t alinro/docker-multi-client ./client
      - run: docker build -t alinro/docker-multi-nginx ./nginx
      - run: docker build -t alinro/docker-multi-server ./server
      - run: docker build -t alinro/docker-multi-worker ./worker

      - run: docker push alinro/docker-multi-client
      - run: docker push alinro/docker-multi-nginx
      - run: docker push alinro/docker-multi-server
      - run: docker push alinro/docker-multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          existing_bucket_name: ${{ secrets.BUCKET_NAME }}
          region: ${{ secrets.region }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
