name: Publish Docker images
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t alinro/docker-multi-client ./client
      - run: docker build -t alinro/docker-multi-nginx ./nginx
      - run: docker build -t alinro/docker-multi-server ./server
      - run: docker build -t alinro/docker-multi-worker ./worker

      - run: docker push alinro/docker-multi-client
      - run: docker push alinro/docker-multi-nginx
      - run: docker push alinro/docker-multi-server
      - run: docker push alinro/docker-multi-worker
